#!/bin/bash
# This is a simple build script, place your post-deploy but pre-start commands
# in this script.  This script gets executed directly, so it could be python,
# php, ruby, etc.

JRUBY_VERSION="1.6.5"
TORQUEBOX_BUILD="594"
RACK_ENV="production"

cd ${OPENSHIFT_DATA_DIR}

# Download a JRuby and plonk it next to our jboss.home.dir
if [ ! -d jruby-${JRUBY_VERSION} ]; then
    curl -o jruby-bin-${JRUBY_VERSION}.tar.gz "http://jruby.org.s3.amazonaws.com/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz"
    tar -xzf jruby-bin-${JRUBY_VERSION}.tar.gz
    rm jruby-bin-${JRUBY_VERSION}.tar.gz
    rm -rf jruby-${JRUBY_VERSION}/share/ri/1.8/system/*
    ln -sf jruby-${JRUBY_VERSION} jruby
fi

# Download a TorqueBox distribution and extract the modules
if [ ! -d ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/modules/org/torquebox ] && [ ! -d torquebox-${TORQUEBOX_BUILD}-modules ]; then
    curl -o torquebox-dist-modules.zip "http://repository-torquebox.forge.cloudbees.com/incremental/torquebox/${TORQUEBOX_BUILD}/torquebox-dist-modules.zip"
    unzip -d torquebox-${TORQUEBOX_BUILD}-modules torquebox-dist-modules.zip
    rm torquebox-dist-modules.zip
fi

if [ ! -d ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/modules/org/torquebox ]; then
    # Symlink TorqueBox modules into the app's .openshift/config/modules directory
    mkdir -p ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org
    ln -s ${OPENSHIFT_DATA_DIR}/torquebox-${TORQUEBOX_BUILD}-modules/torquebox ${OPENSHIFT_REPO_DIR}/.openshift/config/modules/org/torquebox
fi

# Add jruby to our path
export PATH=${OPENSHIFT_DATA_DIR}/jruby/bin:$PATH

# Set JRUBY_HOME if we need to
if ! grep 'jruby.home' ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/bin/standalone.conf > /dev/null; then
    # Copy the symlinked file to a new file
    mv ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/bin/standalone.conf ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/bin/standalone.conf.original
    cp ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/bin/standalone.conf.original ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/bin/standalone.conf
    echo "JAVA_OPTS=\"\$JAVA_OPTS -Djruby.home=${OPENSHIFT_DATA_DIR}jruby\"" >> ${OPENSHIFT_APP_DIR}${OPENSHIFT_APP_TYPE}/bin/standalone.conf
else
    echo "jruby.home has already been set."
fi

# Install Bundler if needed
if ! jruby -S gem list | grep bundler > /dev/null; then
    jruby -S gem install bundler
fi

# Install Rack if needed
if ! jruby -S gem list | grep rack > /dev/null; then
    jruby -S gem install rack
fi

# Install the TorqueBox gems if needed
if ! jruby -S gem list | grep "torquebox (2.x.incremental.${TORQUEBOX_BUILD})" > /dev/null; then
    jruby -S gem install torquebox --pre --source http://torquebox.org/2x/builds/${TORQUEBOX_BUILD}/gem-repo/
fi

# If .bundle isn't currently committed and a Gemfile is then bundle install
if [ ! -d ${OPENSHIFT_REPO_DIR}/.bundle ] && [ -f ${OPENSHIFT_REPO_DIR}/Gemfile ]; then
    jruby -J-Xmx256m -S bundle install --gemfile ${OPENSHIFT_REPO_DIR}/Gemfile
fi

# Ensure a deployments directory exists
mkdir -p ${OPENSHIFT_REPO_DIR}/deployments

# Create a deployment descriptor for this app
cat <<__EOF__ > ${OPENSHIFT_REPO_DIR}/deployments/app-knob.yml
--- 
application: 
  root: ${OPENSHIFT_REPO_DIR}
environment:
  RACK_ENV: ${RACK_ENV}
__EOF__
touch ${OPENSHIFT_REPO_DIR}/deployments/app-knob.yml.dodeploy
